"""initial migration

Revision ID: 7efdc169f59e
Revises: e53f1df2fad6
Create Date: 2016-11-20 22:46:54.224769

"""

# revision identifiers, used by Alembic.
revision = '7efdc169f59e'
down_revision = 'e53f1df2fad6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
