"""initial migration

Revision ID: c9c7257716e9
Revises: 91f3f16b65c7
Create Date: 2016-11-13 19:55:41.400068

"""

# revision identifiers, used by Alembic.
revision = 'c9c7257716e9'
down_revision = '91f3f16b65c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
