"""initial migration

Revision ID: cfd66fa001d4
Revises: 6f13ae7ba025
Create Date: 2016-11-20 01:02:32.501390

"""

# revision identifiers, used by Alembic.
revision = 'cfd66fa001d4'
down_revision = '6f13ae7ba025'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
